import 'server-only';

import { createClient } from '@/lib/supabase/server';
import { createAdminClient } from '@/lib/supabase/admin';
import { fromDatabase } from '@/lib/money';
import type { RuleType } from '@/schemas/recurring.schema';
import type { ExpectedEvent, ExpectedEventStatus } from '@/types/recurring';

/**
 * Expected events — PHASE-07 §15, §39 to §43.
 *
 * The core distinction this table exists to hold (§4): a recurring rule
 * creates an *expectation*, never a transaction. Nothing here moves a balance.
 * Money moves only when the user records it, at which point the event is
 * linked and marked fulfilled.
 */

type Row = Record<string, unknown>;

const str = (v: unknown): string | null => (typeof v === 'string' ? v : null);

const SELECT = `
  id, recurring_rule_id, event_type, name, amount, currency_code,
  scheduled_date, status, account_id, category_id, actual_transaction_id,
  include_in_forecast, detached_from_rule, source_entity_type, source_entity_id
`;

function toEvent(row: Row): ExpectedEvent {
  return {
    id: String(row.id),
    recurringRuleId: str(row.recurring_rule_id),
    eventType: String(row.event_type) as RuleType,
    name: String(row.name),
    amount: fromDatabase(row.amount as string, String(row.currency_code)),
    scheduledDate: String(row.scheduled_date),
    status: String(row.status) as ExpectedEventStatus,
    accountId: str(row.account_id),
    categoryId: str(row.category_id),
    actualTransactionId: str(row.actual_transaction_id),
    includeInForecast: Boolean(row.include_in_forecast),
    detachedFromRule: Boolean(row.detached_from_rule),
    sourceEntityType: str(row.source_entity_type) as ExpectedEvent['sourceEntityType'],
    sourceEntityId: str(row.source_entity_id),
  };
}

/** Scheduled events in a window, oldest first. RLS scopes the read. */
export async function getUpcomingExpectedEvents(
  from: string,
  to: string,
): Promise<ExpectedEvent[]> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from('expected_events')
    .select(SELECT)
    .gte('scheduled_date', from)
    .lte('scheduled_date', to)
    .order('scheduled_date', { ascending: true })
    .order('id', { ascending: true })
    .limit(1000);

  if (error) throw new Error(`Could not load expected events: ${error.code}`);
  return (data ?? []).map((r) => toEvent(r as Row));
}

/** Every event generated by one rule — the §50 detail view. */
export async function listEventsForRule(ruleId: string): Promise<ExpectedEvent[]> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from('expected_events')
    .select(SELECT)
    .eq('recurring_rule_id', ruleId)
    .order('scheduled_date', { ascending: false })
    .limit(500);

  if (error) throw new Error(`Could not load occurrences: ${error.code}`);
  return (data ?? []).map((r) => toEvent(r as Row));
}

/** Ownership via the RLS-scoped client, before any admin-client write. */
async function assertOwned(id: string): Promise<void> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from('expected_events')
    .select('id')
    .eq('id', id)
    .maybeSingle();

  if (error) throw new Error(`Could not verify this occurrence: ${error.code}`);
  if (!data) throw new Error('That occurrence could not be found.');
}

/**
 * §39, §40 — link an expected event to the transaction that satisfied it.
 *
 * Manual only. §40 permits automatic matching later but is explicit that
 * nothing may auto-link without confirmation: a wrong link silently removes a
 * real obligation from the forecast, which is the failure a user would not
 * think to look for.
 */
export async function fulfillExpectedEvent(
  id: string,
  transactionId: string,
): Promise<void> {
  await assertOwned(id);

  // The transaction must be the user's too — checked through RLS rather than
  // trusted from the form.
  const supabase = await createClient();
  const { data: tx, error: txError } = await supabase
    .from('transactions')
    .select('id')
    .eq('id', transactionId)
    .maybeSingle();

  if (txError) throw new Error(`Could not verify that transaction: ${txError.code}`);
  if (!tx) throw new Error('That transaction could not be found.');

  const admin = createAdminClient();
  const { error } = await admin
    .from('expected_events')
    .update({
      status: 'fulfilled',
      actual_transaction_id: transactionId,
      updated_at: new Date().toISOString(),
    })
    .eq('id', id);

  if (error) throw new Error(`Could not link this occurrence: ${error.code}`);
}

/**
 * §41, §42 — skip or cancel one occurrence.
 *
 * Both leave the rule running; §42 insists the three actions stay distinct:
 * skip one occurrence, pause the rule, end the rule. Marking rather than
 * deleting keeps the history, and stops the generator recreating the row on
 * its next pass — a delete would simply come back.
 */
export async function setEventStatus(
  id: string,
  status: Extract<ExpectedEventStatus, 'skipped' | 'cancelled' | 'scheduled'>,
): Promise<void> {
  await assertOwned(id);
  const admin = createAdminClient();

  const { error } = await admin
    .from('expected_events')
    .update({
      status,
      // Un-skipping must also clear any stale link, or the cross-field check
      // (fulfilled ⇔ transaction set) would be the thing that complains.
      actual_transaction_id: null,
      updated_at: new Date().toISOString(),
    })
    .eq('id', id);

  if (error) throw new Error(`Could not update this occurrence: ${error.code}`);
}

/** §43 — exclude an uncertain event from the projection without skipping it. */
export async function setIncludeInForecast(id: string, include: boolean): Promise<void> {
  await assertOwned(id);
  const admin = createAdminClient();

  const { error } = await admin
    .from('expected_events')
    .update({ include_in_forecast: include, updated_at: new Date().toISOString() })
    .eq('id', id);

  if (error) throw new Error(`Could not update this occurrence: ${error.code}`);
}

/**
 * §40 — candidate transactions for manual fulfilment.
 *
 * "Possible hints: same amount, near scheduled date." Offered as a shortlist
 * the user picks from, never applied automatically: §40 is explicit that
 * nothing may auto-link without confirmation, and a wrong link silently
 * removes a real obligation from the forecast — a failure nobody would think
 * to look for.
 *
 * Ordered by closeness of amount first, then date, so the likeliest match
 * leads. Confirmed transactions only, since a voided one moved no money.
 */
export async function findFulfilmentCandidates(
  event: { scheduledDate: string; amount: { minor: bigint; currency: string } },
  windowDays = 14,
): Promise<Array<{ id: string; date: string; label: string; amount: string }>> {
  const supabase = await createClient();

  const shift = (days: number): string => {
    const t = new Date(`${event.scheduledDate}T00:00:00Z`);
    t.setUTCDate(t.getUTCDate() + days);
    return t.toISOString().slice(0, 10);
  };

  const { data, error } = await supabase
    .from('transactions')
    .select(
      'id, transaction_date, amount, currency_code, merchant_name, description, type',
    )
    .eq('status', 'confirmed')
    .eq('currency_code', event.amount.currency)
    .gte('transaction_date', shift(-windowDays))
    .lte('transaction_date', shift(windowDays))
    .order('transaction_date', { ascending: false })
    .limit(50);

  if (error) throw new Error(`Could not load matching transactions: ${error.code}`);

  const target = event.amount.minor;

  return (data ?? [])
    .map((row) => {
      const r = row as Row;
      const minor = BigInt(Math.round(Number(r.amount) * 100));
      const diff = minor > target ? minor - target : target - minor;
      const dayGap = Math.abs(
        (Date.parse(`${String(r.transaction_date)}T00:00:00Z`) -
          Date.parse(`${event.scheduledDate}T00:00:00Z`)) /
          86_400_000,
      );
      return {
        id: String(r.id),
        date: String(r.transaction_date),
        label:
          str(r.merchant_name) ??
          str(r.description) ??
          `${String(r.type)} on ${String(r.transaction_date)}`,
        amount: String(r.amount),
        diff,
        dayGap,
      };
    })
    .sort((a, b) => (a.diff === b.diff ? a.dayGap - b.dayGap : a.diff < b.diff ? -1 : 1))
    .slice(0, 8)
    .map(({ id, date, label, amount }) => ({ id, date, label, amount }));
}
